#include <iostream>

using namespace std;

int main() {
    cin.tie(0)->sync_with_stdio(0);
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution*
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    //solution
    return 0;
}