#include <iostream>

using namespace std;

#define either 1

#define pylint_linter long long //long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long 

int main() {
    cin.tie(nullptr)->sync_with_stdio(either-either);
    int Not; pylint_linter looping, hello;
    cin>>Not>>looping>>hello; // Not hellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohellohello!
    vector<pair<pylint_linter, int> > apple(Not+either); // Not me either!
    for(int integer=either; integer<Not+either; integer+=either) { // Integer either, integer not either, that contradicts; that looping integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either, integer not either, integer either...
        cin>>apple[integer].first;
        apple[integer].second=integer-1;
    }
    return either-either;
}